### ISSUE TITLE
Oskar responds to me with random letters

### ISSUE THREAD

**Issue by hiongyt** [wearehanno/oskar#14]
![jazz error for marcel](https://cloud.githubusercontent.com/assets/8654175/8644969/de132c8e-2975-11e5-9ca0-68ddc0d00a17.jpg)

**Comment by jonlay** [comment]
@marcelkalveram i might be wrong (excuse my bad JS) but I was tinkering with this today because I had the same problem on my testing env, and I think this is down to Hiong not being onboarded fully, and then falling into an issue with your randomisation on responses.

When I tried some console logging to see what type of message Oskar was trying to send, he revealed that it was a `firstMessageFailure`. So the following line:

    else statusMsg = OskarTexts[messageType][random-1]

Is actually trying to do something like:

    else statusMsg = OskarTexts["firstMessageFailure"][random-1]

Which starts to fail, as you'd expect, since there is only 1 option in the `firstMessageSuccess` and `firstMessageFailure`. I assume it's grabbing a random letter from the string, instead of a random array value.

I am pretty sure this is the solution. There's perhaps a separate issue with the onboarding handler not being fired, but that might just be on my local env.

As a possible solution, I removed randomisation on some messages for now... but perhaps we can add this back later, when we have a better solution, and don't need a fixed number of responses (3) from Oskar?

**Comment by marcelkalveram** [comment]
I'll fix that by checking for array length and not forcing every array to contain 3 options.

**Comment by marcelkalveram** [comment]
Should be fixed with commit cbadc71

**Comment by jonlay** [comment]
Hey, perhaps you'll wanna restore some of the messages I removed in 38e444f

**Comment by marcelkalveram** [comment]
Oh ok, I thought you had removed them deliberately. I'll have to leave this open as this requires a bit more work :D

**Comment by marcelkalveram** [comment]
Readded them and made sure that oskar chooses them randomly based on array length.
