### ISSUE TITLE
Restrict update messages to private groups instead of channels?

### ISSUE THREAD

**Issue by seanjohnson** [wearehanno/oskar#18]
We'd love to use this to keep exec teams updated, but don't want updates to have to be broadcasted to the whole company. Can we use groups instead of channels for those updates?

**Comment by jonlay** [comment]
Hey @seanjohnson!

Unfortunately @marcelkalveram (who's the maintainer of this repo) is offline for his summer holiday for another 2 weeks. 

There's the option to set a `CHANNEL_ID`, which is probably what you've found. I don't think the app will currently allow you to set a group, unfortunately. If you're a developer yourself, you're more than welcome to submit a PR for this, as it sounds like a good feature to have in place.

If you're not, then I'll see if Marcel has time when he's back from his break to look into this. The current CHANNEL_ID setting is quite technical anyway, since I don't think it's possible to get the IDs from anywhere but the API, so we probably do have a bit of work to do here to allow people to specify the channel name as a text string, rather than an ID number, anyway.

Sorry to not be able to offer a faster fix :disappointed:

**Comment by jonlay** [comment]
@marcelkalveram just pondering a slightly better way to handle this request...

When you add many integrations to Slack, you're given a choice in the Slack admin area of which channel/group you want to post updates to.

Perhaps it would make sense to use this technique and start to move some of the settings we are handling via Heroku configuration, into the user-friendly Slack integration panel, a bit like this:

![2015-10-28 09 18 29 am](https://cloud.githubusercontent.com/assets/1898889/10784236/e12f019e-7d54-11e5-8990-fe87566a2ed0.png)

Will be interesting to see if it's possible to handle the `DISABLED_CHANNELS` and `DISABLED_USERS` this way, too.

**Comment by marcelkalveram** [comment]
@seanjohnson You should be able to use the current functionality to post to groups as well. Have you tried retrieving your group ID here and then using it as the ```channelID```? https://api.slack.com/methods/groups.list/test

According to the API (https://api.slack.com/methods/chat.postMessage) the method that I'm using works for channels as well as private groups.

@jonlay I'm afraid that way of configuring isn't possible yet because Oskar is not an application. When you want to use it you just set up a new Slackbot, and that doesn't allow for configuration options like this.

**Comment by jonlay** [comment]
Ah, fantastic--being able to grab that list of channels and IDs via the Slack web API is great from my POV. Now that this is in the README, I'm happy!

Let's now mark this as closed and if @seanjohnson has any further issues, he can re-open things.
