### ISSUE TITLE
Official avatar/profile image for the bot

### ISSUE THREAD

**Issue by devinus** [wearehanno/oskar#30]

**Comment by marcelkalveram** [comment]
At the moment, there's no official logo for Oskar, sorry. What would you need it for?

**Comment by jonlay** [comment]
Hey @devinus. I think our intention (apart from simply not getting around to this yet) was that people would pick whatever  image they fancied. On our internal Slack, we're actually using a photo of one of the team's dogs, and 'Oskar' is actually called 'Jazz" (since that's the dog's name).

But agree it'd be simpler if people didn't have to worry about it! We'll stick it on the official list of enhancements to get around to when we've got a bit more time :smile:
