### ISSUE TITLE
Oskar isn't approaching us to ask for feedback (and users are missing from the MongoDB)

### ISSUE THREAD

**Issue by devinus** [wearehanno/oskar#31]
Using a Heroku deploy:

<img width="686" alt="screen shot 2015-11-11 at 8 08 28 pm" src="https://cloud.githubusercontent.com/assets/4836/11108828/1b8843f8-88b0-11e5-852d-42e153e41c62.png">
<img width="689" alt="screen shot 2015-11-11 at 8 08 40 pm" src="https://cloud.githubusercontent.com/assets/4836/11108830/1fb0a2d6-88b0-11e5-9653-5ffd0a5d41ec.png">
<img width="1248" alt="screen shot 2015-11-11 at 8 08 49 pm" src="https://cloud.githubusercontent.com/assets/4836/11108832/240b6bea-88b0-11e5-8b72-1b3fb8a149c8.png">

**Comment by marcelkalveram** [comment]
Sorry to hear that it's not working from you.

From the screenshot though I can see that it behaves as expected. I guess that it can't tell you the status of any of your colleagues yet because they haven't submitted any status. In order to see the status of the whole team you'd ask "how is @channel".

Then it asks you for a number which is correct, but you reply with a string that is not a number, so it tells you that it only understands numbers. As you can see, after posting "1", it tells you it's gonna disappear for a bit. That part seems to require some optimisation as it doesn't ask for a status message, but still accepts answers from your side. I'm gonna try and fix this behaviour as it's a bit unexpected.

Every time you give it a number between 1 and 5 it asks you for a feedback message. And after receiving that feedback messages, it broadcasts the message to the team. Have you configured the broadcast channel correctly as described in the readme, and do any messages show up there?

As for the dashboard, I'm confused why it doesn't show your current status there. Would you mind having a look at your MongoDB and tell me if it's saved anything in there?

Thanks a lot for your feedback, and hope to be able to fix up those bugs very soon. Sorry that your first encounter with Oskar hasn't been as smooth as you expected.

**Comment by devinus** [comment]
We've had Oskar running for two days, but it hasn't asked us any questions unless we prompt it. We've tried relaunching on Heroku 3 times using the Heroku deploy button in the README, following the instructions.

I'm not sure how to diagnose it.
<img width="699" alt="screen shot 2015-11-12 at 1 25 48 pm" src="https://cloud.githubusercontent.com/assets/4836/11128677/f0fd5d62-8940-11e5-9103-9d3718319e32.png">

**Comment by devinus** [comment]
There seems to be only 2 out of our 6 non-disabled users in the DB and nothing else.

**Comment by jonlay** [comment]
I've actually noticed this on our internal Oskar too, @marcelkalveram (that he's a bit less chatty in the last week or two). I think this may be since we deployed the latest commit on `master`.

@devinus just to say that if you ask "How is @general", that won't work. When the README says that you need to ask "How is @channel", that's not supposed to be a dynamic @ name. You really do have to ask "How is @channel".

This is probably confusing and we should come up with a different string to ask for this info, since Oskar isn't tightly tied to any channels. I'll add a new enhancement for this :smile:

**Comment by jonlay** [comment]
@devinus for your remaining 4 non-disabled users, could you look to see what happens if they try saying something to Oskar. Are they then added to the DB?

I hypothesise that connected to this bug, there is a case where Oskar won't approach people directly, and if they haven't spoken to him somehow, he won't have added them to his DB.

**Comment by devinus** [comment]
@jonlay They definitely aren't added to the DB. It seemed random that only 2 of them were. They all reported being spammed by Oskar when they had already answered, and I definitely wasn't in the DB even though, as you can see, I was spamming Oskar.

Nobody got onboarding instructions when Oskar was first deployed either.

**Comment by jonlay** [comment]
Cool, that's weird. I definitely think there is an onboarding issue, as we've seen something internally too.

Let's see if @marcelkalveram can take a look, but I know it may take him a bit of time as we're not working on Oskar full-time at the moment, since he's a side-project of ours.

**Comment by jonlay** [comment]
Sorry for the issues, btw :/

**Comment by devinus** [comment]
No problem. I'm just trying to figure out what's wrong. :) Really like the concept.

**Comment by marcelkalveram** [comment]
@devinus Before I look into the code and ask for more feedback, could you make sure that the dyno is not shutting down after some time? 

That usually happens on free Heroku accounts (https://devcenter.heroku.com/articles/dyno-sleeping#quota) where the app shuts down after a few minutes of inactivity. One possibility to keep it alive is using an app such as http://kaffeine.herokuapp.com/ but since Heroku has introduced that 18 hour limit it's still going to sleep for at least 6hrs/day.

**Comment by devinus** [comment]
@marcelkalveram I ping the app using the dashboard URL before i start interacting with Oskar.

**Comment by marcelkalveram** [comment]
I think the problem was that when running Oskar on free Heroku accounts it wasn't properly retaining the onboarding status in memory. Even though the first thing that it does on init is get the onboarding status from Mongo and save it in memory, it could still happen that it pinged the user for feedback before figuring it if he's onboarded or not, and that's why it would spam people with the wrong message.

I've recently refactored all the modules and fixed a few bugs. Maybe you can give it another try?

Thanks for your patience. I haven't been able to look into Oskar for a long time, unfortunately.
